services:
  - type: web
    name: task-manager
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000 